name = "shortener"
type = "rust"
workers_dev = true
compatibility_date = "2024-11-28" # required
main   = "build/worker/shim.mjs"

[vars]
HOME = "https://jakeswenson.com"

[build]
command = "cargo install -q worker-build && worker-build --release"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration

[[kv_namespaces]]
binding = "urls"
preview_id = "baa83c0aaabb42b0ab77896cb006d8f5"
id = "bba83c0aaabb42b0ab77896cb006d8f5"

[observability]
enabled = true

logs = { enabled = true }
